##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

windowrule = match:class ^(code)$, opacity 0.90
windowrule = match:class ^(mcpelauncher-client)$, float false
windowrule = match:class ^(discord)$, opacity 0.90

windowrule {
  name = Pantalla en pantalla
  match:title = ^(Pantalla\sen\spantalla)$

  float = true
  size = 433 244
  move = 995 644
}

windowrule {
  name = float kitty
  match:class = ^(float_kitty)$

  float = true
  size = 720 450
}
windowrule {
  name = thunar
  match:class = ^(thunar)$

  float = true
  size = 960 600
}
windowrule {
  name = FileRoller
  match:class = ^(org.gnome.FileRoller)$

  float = true
  size = 960 600
}
windowrule {
  name = Abrir carpeta
  match:title = ^(Abrir\scarpeta)$

  float = true
  size = 960 600
}
windowrule {
  name = Abrir archivo
  match:title = ^(Abrir\sarchivo)$

  float = true
  size = 960 600
}