cursor #ff0000

selection_background #330000
selection_foreground #ffffff

# ANSI normal — brillante con sesgo rojo
color0  #221818
color1  #ff3030
color2  #6bff6b
color3  #ffc04d
color4  #6f8fff
color5  #ff6fd3
color6  #6fe0ff
color7  #f0dede

# ANSI bright — muy vivos
color8  #442a2a
color9  #ff0000
color10 #8aff8a
color11 #ffd966
color12 #8fb0ff
color13 #ff8ae0
color14 #8feaff
color15 #ffffff

active_border_color #ff0000
inactive_border_color #552222
bell_border_color #ff4040
