# SUPER key
$mainMod = SUPER

# Actions
bind = ALT, F4, exec, ~/.config/hypr/scripts/altF4.sh
bind = $mainMod, K, exit,
bind = $mainMod SHIFT, V, togglefloating,
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, J, togglesplit, # dwindle
bind = $mainMod, H, fullscreen # Open the window in fullscreen


# Move focus with mainMod + arrow keys
bind = $mainMod SHIFT, left, movefocus, l
bind = $mainMod SHIFT, right, movefocus, r
bind = $mainMod SHIFT, up, movefocus, u
bind = $mainMod SHIFT, down, movefocus, d

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, right, workspace, e+1
bind = $mainMod, left, workspace, e-1

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1 # Scroll workspaces 
bind = $mainMod, mouse_up, workspace, e-1 # Scroll workspaces


# NUM KEYS

bind = $mainMod, code:87, workspace, 1
bind = $mainMod, code:88, workspace, 2
bind = $mainMod, code:89, workspace, 3
bind = $mainMod, code:83, workspace, 4
bind = $mainMod, code:84, workspace, 5
bind = $mainMod, code:85, workspace, 6
bind = $mainMod, code:79, workspace, 7
bind = $mainMod, code:80, workspace, 8
bind = $mainMod, code:81, workspace, 9
bind = $mainMod, code:90, workspace, 10

bind = $mainMod SHIFT, code:87, movetoworkspace, 1
bind = $mainMod SHIFT, code:88, movetoworkspace, 2
bind = $mainMod SHIFT, code:89, movetoworkspace, 3
bind = $mainMod SHIFT, code:83, movetoworkspace, 4
bind = $mainMod SHIFT, code:84, movetoworkspace, 5
bind = $mainMod SHIFT, code:85, movetoworkspace, 6
bind = $mainMod SHIFT, code:79, movetoworkspace, 7
bind = $mainMod SHIFT, code:80, movetoworkspace, 8
bind = $mainMod SHIFT, code:81, movetoworkspace, 9
bind = $mainMod SHIFT, code:90, movetoworkspace, 10

bind = $mainMod, code:91, workspace, e-1
bind = $mainMod, code:104, workspace, e+1


# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow # Move window
bindm = $mainMod, mouse:273, resizewindow # Resize window

# Lid
bindl= , switch:off:Lid Switch, exec, systemctl suspend
