background #000000
foreground #eaffff

cursor #ad8ee6
cursor_text_color #000000

selection_background #003333
selection_foreground #ffffff

# ANSI normal — brillante con sesgo cyan
color0  #182222
color1  #ff6b6b
color2  #4dffaa
color3  #e6ff66
color4  #3ba3ff
color5  #d36bff
color6  #00f0ff
color7  #def6f6

# ANSI bright — muy vivos
color8  #2a4444
color9  #ff8a8a
color10 #66ffc2
color11 #f0ff8a
color12 #66c2ff
color13 #e08aff
color14 #00ffff
color15 #ffffff

active_border_color #00ffff
inactive_border_color #225555
bell_border_color #66ffff
